### ISSUE TITLE
Add resources and methods for admin company addresses

### ISSUE THREAD

**Issue by OdinsPlasmaRifle** [rehive/rehive-python#84]
Add resources and methods for admin company addresses.

We need an SDK resource for doing the following:

```python
account = rehive.admin.company.address.get()
```

This needs to be a resource that can be used to access:

- `admin/company/address/` - GET/PUT/PATCH

**Comment by almabud2** [comment]
This things can be done by this **APIUserAddress**  resource. But I create a new resource **APIAdminCompanyAddress** . I was thinking that if any customization done in the **APIUserAddress** for serving the user addresses only. Then the **company address** can be broke or possibility to break. That's why created a new resource. @OdinsPlasmaRifle @ConnorMac
